### ISSUE TITLE
Can you add jmeter plug-ins?

### ISSUE THREAD

**Issue by grahambunce** [QAInsights/jmeter511#1]
From the docker file I don't think this contains the jmeter plugins. Can you add them as per this linux image:

egaillardon/jmeter-plugins

Many thanks for this - and I'll buy you a tea if you do :)

**Comment by QAInsights** [comment]
It will be released soon :)

**Comment by QAInsights** [comment]
@grahambunce Please check this repo for JMeter plugins. https://github.com/QAInsights/windows-docker-jmeter-plugins Thanks :)
