### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by sivanarayana494** [QAInsights/jmeter511#2]
When I try to run existing script (CSVSample.jmx) it was not running. And I try to run my own script, we are getting below error.
<img width="664" alt="Capture" src="https://user-images.githubusercontent.com/29274484/88545937-4a827b80-d039-11ea-9515-86aec74e1749.PNG">

**Comment by QAInsights** [comment]
You have to mount the volume in which the script is located. From your screenshot, I can see that the JMX execution is successful.
